// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPBbT9_52_8rU5U5PxhQcDhD0B8gkt3Js',
    appId: '1:365526642043:web:79d93c2841448f1d12a1de',
    messagingSenderId: '365526642043',
    projectId: 'smart-attendance-sys-metu',
    authDomain: 'smart-attendance-sys-metu.firebaseapp.com',
    storageBucket: 'smart-attendance-sys-metu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUAlFs19mqkZ2ZIiEpvlNAsLp9bevFTPk',
    appId: '1:365526642043:android:b1be2886a0dfb8f512a1de',
    messagingSenderId: '365526642043',
    projectId: 'smart-attendance-sys-metu',
    storageBucket: 'smart-attendance-sys-metu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmvZdoQblak6URgyI9hHU34S38No996kw',
    appId: '1:365526642043:ios:428eac7944a1966412a1de',
    messagingSenderId: '365526642043',
    projectId: 'smart-attendance-sys-metu',
    storageBucket: 'smart-attendance-sys-metu.firebasestorage.app',
    iosBundleId: 'com.example.smartAtteSys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmvZdoQblak6URgyI9hHU34S38No996kw',
    appId: '1:365526642043:ios:428eac7944a1966412a1de',
    messagingSenderId: '365526642043',
    projectId: 'smart-attendance-sys-metu',
    storageBucket: 'smart-attendance-sys-metu.firebasestorage.app',
    iosBundleId: 'com.example.smartAtteSys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPBbT9_52_8rU5U5PxhQcDhD0B8gkt3Js',
    appId: '1:365526642043:web:e1fc993cd5b9e31b12a1de',
    messagingSenderId: '365526642043',
    projectId: 'smart-attendance-sys-metu',
    authDomain: 'smart-attendance-sys-metu.firebaseapp.com',
    storageBucket: 'smart-attendance-sys-metu.firebasestorage.app',
  );

}